---
- hosts: all
  tasks:
    - name: delete old deployment
      command: kubectl delete -f /home/ubuntu/deployment.yml

    - name: delete old service
      command: kubectl delete -f /home/ubuntu/service.yml

    - name: create new deployment
      command: kubectl apply -f /home/ubuntu/deployment.yml

    - name: installing metal lb
      command: kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.12/config/manifests/metallb-native.yaml

    - name: applying metal lb service
      command: kubectl apply -f /home/ubuntu/metallb-config.yml

    - name: create new service
      command: kubectl apply -f /home/ubuntu/service.yml
