kind: Deployment
apiVersion: apps/v1
metadata:
  name: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web-cont
          image: maeltohamy/pipline-demo
          imagePullPolicy: Always
          ports:
            - containerPort: 80
